{% set name = "azure-data-tables" %}
{% set version = "12.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-data-tables-{{ version }}.zip
  sha256: 3b3d5d15b2a963e09b4934b1fe2ba217f29dd9ac51821c17549fcaf874702434

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - azure-core <2.0.0,>=1.15.0
    - msrest >=0.6.21
    - python >=3.6
    - yarl >=1.0,<2.0

test:
  imports:
    - azure.data.tables
    - azure.data.tables._generated
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/table/azure-table
  summary: Microsoft Azure Azure Data Tables Client Library for Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ngam
    - TomAugspurger
