{% set name = "azure-data-tables" %}
{% set version = "12.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: dd5fc8de91e2f8908efa4c64ca7f63cf83b3068a9ba426298de3b54139e9665c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - azure-core >=1.15.0,<2.0.0
    - msrest >=0.6.21

test:
  imports:
    - azure.data.tables
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/table/azure-table
  summary: Microsoft Azure Azure Data Tables Client Library for Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ngam
    - TomAugspurger
